### ISSUE TITLE
Can't install piretateplayer on raspbian

### ISSUE THREAD

**Issue by Fantomas13** [TestDotCom/pirateplayer#3]
Hello,

what are the commands to install the pirateplayer on a pi 4 raspbian?
 I have a pi 4 with installed
Raspberry Pi OS Lite
Release date: January 11th 2021
Kernel version: 5.4
Size: 438MB

Do I need to install the dev environment to use Pirateplayer?

Pip is installed
pip3, too.
python3, too.

when i use 
`sudo pip install pirateplayer`

I get

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pirateplayer
  Could not find a version that satisfies the requirement pirateplayer (from versions: )
No matching distribution found for pirateplayer

And the command for gstreamer on their page

`apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 `gstreamer1.0-pulseaudio`

is not working properly.

Thanks for answer

**Comment by testdotcom** [comment]
> Do I need to install the dev environment to use Pirateplayer?
Dev environment is only needed if you want to build from sources, but to run pirateplayer you still have to install the requirements (from readme)

What error do you get when you try to install gstreamer dependencies?

**Comment by Fantomas13** [comment]
Hello TestDotCom,

when I visit the website from gstreamer there is an example command to install under Ubuntu/ Debian

https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

`apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio`

When I put the command with sudo, I get

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gstreamer1.0-qt5
E: Couldn't find any package by glob 'gstreamer1.0-qt5'
E: Couldn't find any package by regex 'gstreamer1.0-qt5'


I am able to install every single package, but gstreamer1.0-qt5 does not work and I get the answer above.

**Comment by andygmassey** [comment]
Plus 1 (and a N00b!)

Same issues as @Fantomas13 

On an RPi Zero using:
"Raspberry Pi OS with desktop and recommended software"
Release January 11th 2021
Kernel version: 5.4

My understanding is GStreamer is included in Raspian. 
`gst-launch-1.0 --gst-version`
returns:
`GStreamer Core Library version 1.14.4`

Tried same command as @Fantomas13 in last post, and got exactly same result.

Latest version of GStreamer appears to be 1.18.3, but decided to try with 1.14.4 since couldn't get that command to work.

Tried to follow the instructions on your linked [HiFiBerry](https://www.hifiberry.com/docs/software/configuring-linux-3-18-x) page. Found `/boot/config.txt` already had `dtparam=audio=on` commented out, and the line `dtoverlay=hifiberry-dac` was already there.

`aplay -l` returned this:

`**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 [HifiBerry DAC HiFi pcm5102a-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0`
– so assume all good. 

Installed mplayer even though wasn't sure if it was needed.

Tried to run:
`gobject-introspection libgirepository1.0-dev libcairo2-dev`
but received:
`-bash: gobject-introspection: command not found`

Unsure what to do now, or if that command isn't working because not running correct version of GStreamer (doubtful)...

**Comment by testdotcom** [comment]
Sorry guys but I'm pretty busy right now with personal stuff, however I'll try to help you if I can.

Have you tried to use pirateplayer without the gstreamer1.0-qt5 dependency? Keep in mind those instructions (from HIFIberry and gstreamer) may be outdated, if you have these kind of problems you should try to contact them

**Comment by andygmassey** [comment]
No worries @TestDotCom.

I actually managed to get it working after _a lot_ of effort. Let me post my thoughts and what I did here for others' benefit (if you don't mind me saying, your instructions are a bit too 'light' for n00bs like me!):

**Not directly related set-up**
1. I used the Desktop version of Raspberry Pi OS, not Lite version.
2. Did `sudo apt update` and `sudo apt upgrade`
3. Followed the [Pimoroni instructions to install their Pimoroni Pirate Audio software](https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-pirate-audio)
4. Instructions said that you should see a little message on the display of your Pirate Audio board telling you to go to an URL – but it didn't. Actually needed to [disable onboard audio](https://forums.pimoroni.com/t/no-sound-from-pirate-audio-smol-speaker/12223/2) before it would work.
5. Found it challenging to easily add sound files, so ended up [installing appletalk protocol on the Pi ](https://raspberrypi.stackexchange.com/questions/8950/copy-files-from-osx-to-from-pi) using `sudo apt-get install netatalk`. Then editing `/etc/netatalk/afp.conf` – changed this line: `basedir regex = /home`
6. On Mac, in Terminal: `open afp://172.20.10.10` – asks to authenticate, and then easy to copy files from Finder to RPi.

**PiratePlayer set-up**
7. [PiratePlayer GitHub](https://github.com/TestDotCom/pirateplayer) page says that [GStreamer](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html) and [HiFiBerry](https://www.hifiberry.com/docs/software/configuring-linux-3-18-x) are dependencies.
8. Using `gst-launch-1.0 --gst-version` returned `GStreamer Core Library version 1.14.4`. Latest version as of this post is 1.18.3, but I couldn't work out how to upgrade it, so didn't and just proceeded without. 
9. Following the HiFiBerry instructions I edited `/boot/config.txt` – checked that this line was commented out: `dtparam=audio=on` and added this line `dtoverlay=hifiberry-dac`.
10. Did a check that the sound card is enabled: `aplay -l` returned:

```
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 [HifiBerry DAC HiFi pcm5102a-hifi-0]
Subdevices: 1/1
Subdevice #0: subdevice #0
```

11. Wasn't sure if it was needed or not, but installed mplayer: `sudo apt-get install mplayer`.
12. I couldn't get `gobject-introspection libgirepository1.0-dev libcairo2-dev` to run, per the PiratePlayer instructions. Eventually figured out I didn't have the right version of Python and/or some other things. Did `python --version` which returned 2.7.16 – whereas PiratePlayer requires 3.5+.
13. So [installed Python 3](https://docs.python-guide.org/starting/install3/linux/#install3-linux) using `sudo apt-get update` and then `sudo apt-get install python3.6`.
14. Installed Pipenv: `pip3 install --user pipenv`
15. Found the user base binary directory by running   `python3 -m site --user-base` . This returned `/home/pi/.local`
16. Understood I needed to add `~/.local/bin` to my `PATH`. Set it permanently by modifying `~/.profile `and adding `export PATH="$PATH:/home/pi/.local/bin"` to the end.
17. Had to source it to do an update (doesn't do automatically): `source /home/pi/.profile`
18.  Installed [Requests](http://docs.python-requests.org/en/master/) library and created a Pipfile in project directory:

```
mkdir /home/pi/PiratePlayer
cd PiratePlayer
pipenv install requests
```
19. Tried to set up a dev environment according to the four commands provided at [PiratePlayer page](https://pypi.org/project/pirateplayer/), but failed miserably. The command `pip3 install --editable . `returned `ERROR: File "setup.py" not found. `
20. Ran the PiratePlayer install command, but with pip3 rather than pip: `pip3 install pirateplayer`
21. Upgraded pip and other tools: `python -mpipinstall --upgradepipsetuptoolswheel`
22. Had exactly the [same error mentioned here](https://github.com/numpy/numpy/issues/14772) when I tried to run PiratePlayer.
23. Used [Mattip](https://github.com/mattip)'s suggestion, and ran: `sudo apt-get install libatlas-base-dev`
24. Tried to run PiratePlayer again, but got exactly the [same error as this](https://forums.pimoroni.com/t/pirate-player-for-pirate-audio/15222). 
25. Followed [terminalpi](https://forums.pimoroni.com/u/terminalpi/summary)'s recommendation and created a file `/home/pi/.config/pirateplayer/conf.ini `with this contents:

```
[PLAYER]
root = ~/Music

[BUTTON]
a = 5
b = 6
x = 16
y = 20
```

26. Re-ran PiratePlayer again, and it kind of half worked, but threw errors when certain of the Pirate Audio push buttons were pressed. 
27. Thought it was because GPIOZero wasn't installed properly, but after [following the instructions here](https://gpiozero.readthedocs.io/en/stable/installing.html) and doing another `sudo apt update` and `sudo apt upgrade`, after running `sudo apt install python3-gpiozero` I got `python3-gpiozero is already the newest version (1.5.1)`. So guess it wasn't that.
28. PiratePlayer instructions say "enable GPIO SPI - check [RPiconfig](https://elinux.org/RPiconfig) if not sure how" – but that page is extremely long... Finally realised that under “Device Tree” it says to "enable I2C on GPIO pins” need to have this: `dtparam=i2c_arm=on` on.
29. So edited  `/boot/config.txt` and uncommented `dtparam=i2c_arm=on`. The line `dtparam=spi=on`  was already uncommented.
30. Still got an error when I tried to run PiratePlayer, but realised that it was probably due to what [alphanumeric said](https://forums.pimoroni.com/t/pirate-player-for-pirate-audio/15222/3?u=andymassey), so changed `/home/pi/.config/pirateplayer/conf.ini `line `y = 20`  to  `y = 24`.
31. Ran `pirateplayer` again, and it finally worked!!


Hope this helps someone save the ~8 hours that it took me!! Apologies if my explanation is verbose or not properly formatted – first time writing one of these posts.

**Comment by Fantomas13** [comment]
@andygmassey 

First, Thank you for the detailed instructions.

I have 3 questions:

1. Did you deinstalled the PirateAudioSoftware again after Step 3?
2. Before Step 19 you installed pip3, or?
3. when you didn't deinstalled PirateAudioSoftware, which changes did you make in order to start pirateplayer and ignore PirateAudioSoftware


Thx

**Comment by andygmassey** [comment]
Hey there @Fantomas13 

No problem, hope it helps. 

1. No, didn’t deinstall.
2. pip3 is installed with Python 3 (step 13)
3. Didn’t make any changes. But I did have it plugged in to a screen - so used the desktop to open pirateplayer after boot (but also successfully did it via ssh). The Pirate Audio URL will still appear on the LCD at boot, but will disappear when you run pirateplayer.

**Comment by testdotcom** [comment]
I'm glad to see you were able to solve these problems, well done! I'm going to close and hopefully it can help others.

@andygmassey by the way, you are not a total n00b, you just need more experience :)

**Comment by christomcneil** [comment]
Many thanks @andygmassey and @TestDotCom for getting this to work. If you're a n00b Andy, i'm not sure what that makes me!
